### ISSUE TITLE
Provide UI to work with versions and audit entries

### ISSUE THREAD

**Issue by bosschaert** [adobe/da-live#108]
We need the UI to work with Versions https://github.com/adobe/da-admin/issues/6 and Audit entries https://github.com/adobe/da-admin/issues/5

**Comment by auniverseaway** [comment]
![Artboard 1](https://github.com/adobe/da-live/assets/1972095/08823edd-fa7e-4109-a2ad-767ef36ec4d1)

**Comment by bosschaert** [comment]
I've updated the `versions` branch to look like the artboard:
<img width="1527" alt="Screenshot 2024-04-24 at 12 34 35" src="https://github.com/adobe/da-live/assets/226514/adc436a3-55c8-4c10-a0b9-34ea536f23db">

I couldn't find the icons on https://spectrum.adobe.com/page/icons/ so I left the old ones for now...  
Also note that there are no named versions yet.

Two questions @auniverseaway :
**How would we expand the list of audit logs at the top that are overflowing and hidden**?
<img width="308" alt="Screenshot 2024-04-24 at 12 37 06" src="https://github.com/adobe/da-live/assets/226514/7bd5abf3-7eae-4922-86b4-0ee06f832d24">

Just reveal them all when clicking on it?

**And how should we make visible the hidden audit log entries for previous dates**?
<img width="271" alt="Screenshot 2024-04-24 at 12 37 10" src="https://github.com/adobe/da-live/assets/226514/6df5542c-2788-4982-bb2a-e9909a52be5c">

Similarly reveal them all when clicking on it?

**Comment by bosschaert** [comment]
I made a first attempt at naming versions. You can see it show up in the version list here beside the green circle. Right now I have a button to name the currently selected version in the toolbar but you probably want to change that 😉 
<img width="564" alt="Screenshot 2024-04-26 at 14 12 09" src="https://github.com/adobe/da-live/assets/226514/f897ff33-3453-4c50-9cd0-e1a936888dec">

@auniverseaway What UI interaction do you have in mind to enter the name for the version?

(note that for this to work some pending changes to da-admin are needed)

**Comment by bosschaert** [comment]
> > Just reveal them all when clicking on it?

> Yup, I think so.

With https://github.com/adobe/da-live/commit/6bd5447ed76b879490ba76ac9906626d310d7abf I added expansion when clicking on it like this:

Initial visual:
<img width="274" alt="Screenshot 2024-04-29 at 14 06 57" src="https://github.com/adobe/da-live/assets/226514/a0db2928-4476-484e-8671-4e50139e9e75">

After clicking on each hidden element:
<img width="297" alt="Screenshot 2024-04-29 at 14 07 06" src="https://github.com/adobe/da-live/assets/226514/4541a43c-82e6-45cd-b6d2-61d7575148bb">

Obviously clicking on an expanded item again will hide it again.

Hopefully this is close to what you had in mind.

Remaining question is how a version is named. The current implementation allows the naming of a selected version by clicking on this button <img width="65" alt="Screenshot 2024-04-29 at 14 20 51" src="https://github.com/adobe/da-live/assets/226514/427ee331-56b7-44fb-842b-3c648241583c">

And then entering the name in a popup dialog. 
<img width="824" alt="Screenshot 2024-04-29 at 14 21 19" src="https://github.com/adobe/da-live/assets/226514/3361273b-0376-41da-9578-28fb0ece9159">

I have the feeling you probably want to visualise that differently. Just let me know.

**Comment by bosschaert** [comment]
With https://github.com/adobe/da-live/commit/544e83403dd1e2eba04361a77a1b95ce69ab4f65 I updated the version naming as follows:

When a new version is created with the top button in the version toolbar an entry appears in the version line with a where the user can type in the version name (using `contenteditable=true`):
<img width="336" alt="Screenshot 2024-04-30 at 16 00 11" src="https://github.com/adobe/da-live/assets/226514/b191cbb1-5c3f-47d5-a73c-d839772ff24b">

When the user hits enter or clicks somewhere else on the screen, the version is stored in the backend.
<img width="292" alt="Screenshot 2024-04-30 at 16 24 46" src="https://github.com/adobe/da-live/assets/226514/78b56533-dc73-48e7-b6bc-327f2186f687">

It's also still possible to select a version and edit the name or give it a name if it didn't have a name before via this button:
<img width="65" alt="Screenshot 2024-04-29 at 14 20 51" src="https://github.com/adobe/da-live/assets/226514/8fe94877-6ea6-4dbd-a48f-c317b3bb76d2">
let me know if you want to keep that or not.

If the user hits Escape the version creation/editing is cancelled.
