### ISSUE TITLE
Triple dash support

### ISSUE THREAD

**Issue by auniverseaway** [adobe/da-live#209]
As an author who uses "View document source" from AEM Sidekick, I would like the ability to copy Word-formatted section breaks and have DA convert them to HRs so I do not have to reformat docs coming from other sources.

## Criteria of acceptance
1. Convert top level `<p>---</p>` to `<hr/>` automatically.
2. Does not convert deep occurrences... in tables, lists, etc. as Helix does not do this.

## Additional thoughts
[We already do this client-side](https://github.com/adobe/da-live/blob/main/blocks/edit/utils/helpers.js#L74-L77) when we send to preview, but it appears we no longer do this with the change over to HAST. 

We could probably format this on paste using a ProseMirror plugin, but for HTML that's been directly uploaded, this won't work.

I'm curious to know what the UX is like... if the editor gets updated in real-time or if they stay as `---`.

**Comment by bosschaert** [comment]
Reopening as the merge was reverted, likely due to an issue with regenerating the `da-y-wrapper` library.
