### ISSUE TITLE
Custom plugins disappearing in library popup

### ISSUE THREAD

**Issue by bosschaert** [adobe/da-live#216]
Sometimes the custom plugins disappear from the library section:
![plugins](https://github.com/user-attachments/assets/ecf23fc0-b143-429f-8075-3fc0cde004bc)

Logging out and logging back makes them re-appear.

**Comment by auniverseaway** [comment]
I'm pretty sure this is related to AEM Sidekick being open in the background and sending conflicting headers for authorization.
