### ISSUE TITLE
Delete hangs forever in UI

### ISSUE THREAD

**Issue by bosschaert** [adobe/da-live#245]
When deleting a file, the UI hangs while showing this dialog forever (it even happens with a single file):

<img width="1194" alt="Screenshot 2024-10-18 at 16 20 48" src="https://github.com/user-attachments/assets/8a82377d-8b1d-4d95-a490-9a98e1be2098">

The file is actually deleted, and a refresh of the window resolves the issue.

This issue is possibly related to #233

**Comment by bosschaert** [comment]
I looked a little bit into this and found that here: https://github.com/adobe/da-live/blob/733208fd4dccad9fd74e41f38acd24f5b74974f6/blocks/browse/da-list/da-list.js#L182 the UI expects a `json()` response from `da-admin`. 

However `da-admin` just sends a 204 with an empty response back, and as far as I can see it has been doing that for a long time: https://github.com/adobe/da-admin/blob/e407d91dfbcc4847c7881ca3b53a83e4b3d88c1f/src/storage/object/delete.js#L97

**Comment by auniverseaway** [comment]
We fixed this at the hackathon.
