### ISSUE TITLE
Unified Search

### ISSUE THREAD

**Issue by docs-dre** [adobe/da-live#54]
**User Story**
As a PM, I would like the ability to do a block search throughout my content repo, so I can easily identify where blocks live throughout my site. 

**Acceptance Criteria**

- There is dedicated functionality to search for blocks that are used throughout the content repo
- For example: User enters content repo, clicks into search bar, enters "marquee", and list of pages using the marquee block is shown

**Value**
- When thinking about bulk changes that may need to occur across the site, this will be a helpful to narrow down the list of pages that may need to altered. Think bulk updating, think introducing consonants latest variant to a block and i want to scale that variant across many different pages

**Comment by auniverseaway** [comment]
What I would love to see is if we can use OpenSearch and have blocks, fragments, and maybe headings as searchable metadata.
