### ISSUE TITLE
Inline Block Creation

### ISSUE THREAD

**Issue by docs-dre** [adobe/da-live#55]
**User Story**
As an author, i would like the ability to create blocks inline of my document, so i can create pages faster without having to rely on the library widget

**Acceptance Criteria**
Non Functional:
- Authors have the ability to create blocks without having to access the library widget
- Authors can instantiate block creation with the click of button (e.g. "/")

Functional:
- Upon instantiating a block, authors are presented with a drop down of block option
- once the block is selected the block will appear on the doc

For example, check out this Notion page:
https://github.com/adobe/da-live/assets/157659174/b7a44995-dbb5-425b-be5f-bfc67276a44e

<img width="573" alt="Screenshot 2024-01-24 at 7 33 21 PM" src="https://github.com/adobe/da-live/assets/157659174/25b72a29-a4d7-405d-b19e-d33c47c8d84c">

**Comment by auniverseaway** [comment]
I feel like you and @davidnuescheler have been talking. This is exactly what he wants instead of the palette.

**Comment by docs-dre** [comment]
Nice! It would be incredibly smooth if we can pull this off
