### ISSUE TITLE
Drag to upload

### ISSUE THREAD

**Issue by auniverseaway** [adobe/da-live#56]
As an author I would like the ability to drag htmls, images, jsons in the `da-browse` block instead of using the create new button so that I can do upload operations faster and in bulk.

## Criteria of acceptance
1. Supports dragging singular documents into the browse block (we can refine specific UX details during dev)
2. Supports dragging multiple files while also retaining the folder structure of dragged items.
3. Does not upload un-supported files (.DS_Store, MOV, MKV, etc)
4. Uploads should be relative to the current location browsing.

## Additional context
We probably need a universal supported file type list in constants.js. The upload image plugin has the beginnings of this.

This unlocks simple content migrations in that someone can do offline edits in bulk (think find & replace a URL or image SRC) and then drag the items back in.

This issue should not be confused with bulk downloads which I think will require broader API support for zipping a series of items.

**Comment by docs-dre** [comment]
@auniverseaway this ticket made me think about a possibility to upload existing word docs straight into a da directory. Some kind of .docx -> .alleydoc converter? to make migrations easier. Not sure if thats what this issue is also trying to get at

**Comment by auniverseaway** [comment]
@docs-dre 100%. There's some interesting implications here.

We get a lot of what you're trying to accomplish for free right now because we store the exact same format as AEM Edge Delivery. This means you can take any page from hlx.page and upload it to DA.

Where this falls down is metadata. Currently, metadata is only separated between Excel and Word. 

1. If you look at the "plain.html" format there is no metadata.
2. If you look at the regular page, you cannot differentiate between inherited and local.
3. If you look at md, you get this, but MD isn't the best format.

I think we want this, but it would probably be later when we have docx migrations.
