### ISSUE TITLE
[Bug] Library Panel Stays open after trying to use other panels

### ISSUE THREAD

**Issue by docs-dre** [adobe/da-live#59]
**Problem Statement**
Currently, when trying to access the tables panel after using the library, the library panel stays open. As a result of this ticket, we should ensure the panels close when a new panel has been opened

**S2R**

1. Go to: https://da.live/edit#/adobecom/da-milo-college/drafts/iscandar/walking-down-an-alley
2. Click on the library panel (dont close it)
3. Attempt to open any new panel
4. Note the library panel staying open

**Actual**
* panel stays open after new panel has been opened

**Expected**
* previous panel should close when new panel is open

<img width="1792" alt="Screenshot 2024-01-31 at 9 04 23 PM" src="https://github.com/adobe/da-live/assets/157659174/54614a3c-4f95-4659-8b6d-401631609ad6">

**Comment by auniverseaway** [comment]
Fixed.
